# Generated by Django 4.2.1 on 2023-07-07 09:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('pesan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesan',
            name='waktu_posting',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
