# Generated by Django 4.2.1 on 2023-07-14 09:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bentuk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bentuk', models.CharField(max_length=50)),
                ('ket', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Jumlah',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jumlah', models.CharField(max_length=50)),
                ('ket', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Collab',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('nama', models.CharField(max_length=50)),
                ('nomor', models.IntegerField()),
                ('brand', models.CharField(max_length=50)),
                ('tentang', models.CharField(max_length=250)),
                ('waktu_posting', models.DateTimeField(auto_now_add=True)),
                ('bentuk_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collab.bentuk')),
                ('jumlah_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collab.jumlah')),
            ],
        ),
    ]
