# Generated by Django 4.2.1 on 2023-07-14 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collab', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bentuk',
            name='bentuk',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='jumlah',
            name='jumlah',
            field=models.CharField(max_length=200),
        ),
    ]
